import { Inter } from 'next/font/google'
import '../styles/main.scss'
import Footer from '@/components/footer/Footer'

import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SAiPH Technologies',
  description: 'Generated by SAiPH',
  icons: {
    icon: ['/favicon.ico?v=1',],
    apple: ['/apple-touch-icon.png?v=1',],
    shortcut:['/apple-touch-icon.png']
  },
  manifest:'/site.webmenifest'
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
        
        <Header/>
        
        {children}
      
      <Footer/>
      </body>
    </html>
  )
}
